# Generated by Django 2.1.7 on 2019-03-09 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(help_text='Enter your content here.', max_length=1800)),
                ('post_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
