# Generated by Django 2.1.7 on 2019-03-11 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog_Author',
        ),
        migrations.AddField(
            model_name='blog_posts',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Blog_User'),
        ),
    ]
